/*
Copyright (C) 2025 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/

export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    screens: {
      xs: '320px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1440px',
      'bp-320': '320px',
      'bp-768': '768px',
      'bp-1024': '1024px',
      'bp-1440': '1440px',
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      'semi-color-white': 'var(--semi-color-white)',
      'semi-color-black': 'var(--semi-color-black)',
      'semi-color-primary': 'var(--semi-color-primary)',
      'semi-color-primary-hover': 'var(--semi-color-primary-hover)',
      'semi-color-primary-active': 'var(--semi-color-primary-active)',
      'semi-color-primary-disabled': 'var(--semi-color-primary-disabled)',
      'semi-color-primary-light-default':
        'var(--semi-color-primary-light-default)',
      'semi-color-primary-light-hover': 'var(--semi-color-primary-light-hover)',
      'semi-color-primary-light-active':
        'var(--semi-color-primary-light-active)',
      'semi-color-secondary': 'var(--semi-color-secondary)',
      'semi-color-secondary-hover': 'var(--semi-color-secondary-hover)',
      'semi-color-secondary-active': 'var(--semi-color-secondary-active)',
      'semi-color-secondary-disabled': 'var(--semi-color-secondary-disabled)',
      'semi-color-secondary-light-default':
        'var(--semi-color-secondary-light-default)',
      'semi-color-secondary-light-hover':
        'var(--semi-color-secondary-light-hover)',
      'semi-color-secondary-light-active':
        'var(--semi-color-secondary-light-active)',
      'semi-color-tertiary': 'var(--semi-color-tertiary)',
      'semi-color-tertiary-hover': 'var(--semi-color-tertiary-hover)',
      'semi-color-tertiary-active': 'var(--semi-color-tertiary-active)',
      'semi-color-tertiary-light-default':
        'var(--semi-color-tertiary-light-default)',
      'semi-color-tertiary-light-hover':
        'var(--semi-color-tertiary-light-hover)',
      'semi-color-tertiary-light-active':
        'var(--semi-color-tertiary-light-active)',
      'semi-color-default': 'var(--semi-color-default)',
      'semi-color-default-hover': 'var(--semi-color-default-hover)',
      'semi-color-default-active': 'var(--semi-color-default-active)',
      'semi-color-info': 'var(--semi-color-info)',
      'semi-color-info-hover': 'var(--semi-color-info-hover)',
      'semi-color-info-active': 'var(--semi-color-info-active)',
      'semi-color-info-disabled': 'var(--semi-color-info-disabled)',
      'semi-color-info-light-default': 'var(--semi-color-info-light-default)',
      'semi-color-info-light-hover': 'var(--semi-color-info-light-hover)',
      'semi-color-info-light-active': 'var(--semi-color-info-light-active)',
      'semi-color-success': 'var(--semi-color-success)',
      'semi-color-success-hover': 'var(--semi-color-success-hover)',
      'semi-color-success-active': 'var(--semi-color-success-active)',
      'semi-color-success-disabled': 'var(--semi-color-success-disabled)',
      'semi-color-success-light-default':
        'var(--semi-color-success-light-default)',
      'semi-color-success-light-hover': 'var(--semi-color-success-light-hover)',
      'semi-color-success-light-active':
        'var(--semi-color-success-light-active)',
      'semi-color-danger': 'var(--semi-color-danger)',
      'semi-color-danger-hover': 'var(--semi-color-danger-hover)',
      'semi-color-danger-active': 'var(--semi-color-danger-active)',
      'semi-color-danger-light-default':
        'var(--semi-color-danger-light-default)',
      'semi-color-danger-light-hover': 'var(--semi-color-danger-light-hover)',
      'semi-color-danger-light-active': 'var(--semi-color-danger-light-active)',
      'semi-color-warning': 'var(--semi-color-warning)',
      'semi-color-warning-hover': 'var(--semi-color-warning-hover)',
      'semi-color-warning-active': 'var(--semi-color-warning-active)',
      'semi-color-warning-light-default':
        'var(--semi-color-warning-light-default)',
      'semi-color-warning-light-hover': 'var(--semi-color-warning-light-hover)',
      'semi-color-warning-light-active':
        'var(--semi-color-warning-light-active)',
      'semi-color-focus-border': 'var(--semi-color-focus-border)',
      'semi-color-disabled-text': 'var(--semi-color-disabled-text)',
      'semi-color-disabled-border': 'var(--semi-color-disabled-border)',
      'semi-color-disabled-bg': 'var(--semi-color-disabled-bg)',
      'semi-color-disabled-fill': 'var(--semi-color-disabled-fill)',
      'semi-color-shadow': 'var(--semi-color-shadow)',
      'semi-color-link': 'var(--semi-color-link)',
      'semi-color-link-hover': 'var(--semi-color-link-hover)',
      'semi-color-link-active': 'var(--semi-color-link-active)',
      'semi-color-link-visited': 'var(--semi-color-link-visited)',
      'semi-color-border': 'var(--semi-color-border)',
      'semi-color-nav-bg': 'var(--semi-color-nav-bg)',
      'semi-color-overlay-bg': 'var(--semi-color-overlay-bg)',
      'semi-color-fill-0': 'var(--semi-color-fill-0)',
      'semi-color-fill-1': 'var(--semi-color-fill-1)',
      'semi-color-fill-2': 'var(--semi-color-fill-2)',
      'semi-color-bg-0': 'var(--semi-color-bg-0)',
      'semi-color-bg-1': 'var(--semi-color-bg-1)',
      'semi-color-bg-2': 'var(--semi-color-bg-2)',
      'semi-color-bg-3': 'var(--semi-color-bg-3)',
      'semi-color-bg-4': 'var(--semi-color-bg-4)',
      'semi-color-text-0': 'var(--semi-color-text-0)',
      'semi-color-text-1': 'var(--semi-color-text-1)',
      'semi-color-text-2': 'var(--semi-color-text-2)',
      'semi-color-text-3': 'var(--semi-color-text-3)',
      'semi-color-highlight-bg': 'var(--semi-color-highlight-bg)',
      'semi-color-highlight': 'var(--semi-color-highlight)',
      'semi-color-data-0': 'var(--semi-color-data-0)',
      'semi-color-data-1': 'var(--semi-color-data-1)',
      'semi-color-data-2': 'var(--semi-color-data-2)',
      'semi-color-data-3': 'var(--semi-color-data-3)',
      'semi-color-data-4': 'var(--semi-color-data-4)',
      'semi-color-data-5': 'var(--semi-color-data-5)',
      'semi-color-data-6': 'var(--semi-color-data-6)',
      'semi-color-data-7': 'var(--semi-color-data-7)',
      'semi-color-data-8': 'var(--semi-color-data-8)',
      'semi-color-data-9': 'var(--semi-color-data-9)',
      'semi-color-data-10': 'var(--semi-color-data-10)',
      'semi-color-data-11': 'var(--semi-color-data-11)',
      'semi-color-data-12': 'var(--semi-color-data-12)',
      'semi-color-data-13': 'var(--semi-color-data-13)',
      'semi-color-data-14': 'var(--semi-color-data-14)',
      'semi-color-data-15': 'var(--semi-color-data-15)',
      'semi-color-data-16': 'var(--semi-color-data-16)',
      'semi-color-data-17': 'var(--semi-color-data-17)',
      'semi-color-data-18': 'var(--semi-color-data-18)',
      'semi-color-data-19': 'var(--semi-color-data-19)',
      'na-canvas': 'var(--na-bg-canvas)',
      'na-surface': 'var(--na-bg-surface)',
      'na-elevated': 'var(--na-bg-elevated)',
      'na-muted': 'var(--na-bg-muted)',
      'na-border': 'var(--na-border-subtle)',
      'na-border-strong': 'var(--na-border-strong)',
      'na-text': 'var(--na-text-primary)',
      'na-text-secondary': 'var(--na-text-secondary)',
      'na-text-tertiary': 'var(--na-text-tertiary)',
      'na-inverse': 'var(--na-text-inverse)',
      'na-accent': 'var(--na-accent-primary)',
      'na-accent-hover': 'var(--na-accent-primary-hover)',
      'na-danger': 'var(--na-color-error)',
      'na-success': 'var(--na-color-success)',
      'na-warning': 'var(--na-color-warning)',
      'na-info': 'var(--na-color-info)',
      white: 'var(--na-color-white)',
      black: 'var(--na-color-near-black)',
      gray: {
        50: 'var(--na-color-ivory)',
        100: 'var(--na-color-border-cream)',
        200: 'var(--na-color-border-warm)',
        300: 'var(--na-color-ring-warm)',
        400: 'var(--na-color-warm-silver)',
        500: 'var(--na-color-stone-gray)',
        600: 'var(--na-color-olive-gray)',
        700: 'var(--na-color-charcoal)',
        800: 'var(--na-color-dark-warm)',
        900: 'var(--na-color-near-black)',
      },
      slate: {
        50: 'var(--na-color-ivory)',
        100: 'var(--na-color-border-cream)',
        200: 'var(--na-color-border-warm)',
        300: 'var(--na-color-ring-warm)',
        400: 'var(--na-color-warm-silver)',
        500: 'var(--na-color-stone-gray)',
        600: 'var(--na-color-olive-gray)',
        700: 'var(--na-color-charcoal)',
        800: 'var(--na-color-dark-warm)',
        900: 'var(--na-color-near-black)',
      },
      zinc: {
        50: 'var(--na-color-ivory)',
        100: 'var(--na-color-border-cream)',
        200: 'var(--na-color-border-warm)',
        300: 'var(--na-color-ring-warm)',
        400: 'var(--na-color-warm-silver)',
        500: 'var(--na-color-stone-gray)',
        600: 'var(--na-color-olive-gray)',
        700: 'var(--na-color-charcoal)',
        800: 'var(--na-color-dark-warm)',
        900: 'var(--na-color-near-black)',
      },
      blue: {
        50: 'var(--semi-color-primary-light-default)',
        100: 'var(--semi-color-primary-light-default)',
        200: 'var(--semi-color-primary-light-hover)',
        300: 'var(--semi-color-primary-light-hover)',
        400: 'var(--na-accent-primary-hover)',
        500: 'var(--na-accent-primary)',
        600: 'var(--na-accent-primary)',
        700: 'var(--na-accent-primary-active)',
        800: 'var(--na-color-dark-warm)',
        900: 'var(--na-color-near-black)',
      },
      purple: {
        50: 'var(--semi-color-primary-light-default)',
        100: 'var(--semi-color-primary-light-default)',
        200: 'var(--semi-color-primary-light-hover)',
        300: 'var(--semi-color-primary-light-hover)',
        400: 'var(--na-accent-primary-hover)',
        500: 'var(--na-accent-primary)',
        600: 'var(--na-accent-primary)',
        700: 'var(--na-accent-primary-active)',
        800: 'var(--na-color-dark-warm)',
        900: 'var(--na-color-near-black)',
      },
      violet: {
        50: 'var(--semi-color-primary-light-default)',
        100: 'var(--semi-color-primary-light-default)',
        500: 'var(--na-accent-primary)',
        600: 'var(--na-accent-primary-active)',
        900: 'var(--na-color-dark-warm)',
      },
      indigo: {
        50: 'var(--semi-color-primary-light-default)',
        100: 'var(--semi-color-primary-light-default)',
        500: 'var(--na-accent-primary)',
        600: 'var(--na-accent-primary-active)',
        900: 'var(--na-color-dark-warm)',
      },
      teal: {
        50: 'var(--semi-color-info-light-default)',
        100: 'var(--semi-color-info-light-default)',
        500: 'var(--na-color-info)',
        600: 'var(--na-color-info)',
        700: 'var(--semi-color-info-active)',
        900: 'var(--na-color-dark-warm)',
      },
      green: {
        50: 'var(--semi-color-success-light-default)',
        100: 'var(--semi-color-success-light-default)',
        500: 'var(--na-color-success)',
        600: 'var(--na-color-success)',
        700: 'var(--semi-color-success-active)',
        900: 'var(--na-color-dark-warm)',
      },
      yellow: {
        50: 'var(--semi-color-warning-light-default)',
        100: 'var(--semi-color-warning-light-default)',
        500: 'var(--na-color-warning)',
        600: 'var(--na-color-warning)',
        700: 'var(--semi-color-warning-active)',
      },
      amber: {
        50: 'var(--semi-color-warning-light-default)',
        100: 'var(--semi-color-warning-light-default)',
        500: 'var(--na-color-warning)',
        600: 'var(--na-color-warning)',
        700: 'var(--semi-color-warning-active)',
      },
      orange: {
        50: 'var(--semi-color-warning-light-default)',
        100: 'var(--semi-color-warning-light-default)',
        500: 'var(--na-accent-primary-hover)',
        600: 'var(--na-accent-primary)',
        700: 'var(--na-accent-primary-active)',
      },
      red: {
        50: 'var(--semi-color-danger-light-default)',
        100: 'var(--semi-color-danger-light-default)',
        500: 'var(--na-color-error)',
        600: 'var(--na-color-error)',
        700: 'var(--semi-color-danger-active)',
        900: 'var(--na-color-dark-warm)',
      },
      rose: {
        50: 'var(--semi-color-danger-light-default)',
        100: 'var(--semi-color-danger-light-default)',
        500: 'var(--na-color-error)',
        600: 'var(--na-color-error)',
        700: 'var(--semi-color-danger-active)',
      },
    },
    spacing: {
      0: 'var(--na-space-0)',
      px: 'var(--na-space-px)',
      0.5: 'var(--na-space-0-5)',
      1: 'var(--na-space-1)',
      1.5: 'var(--na-space-1-5)',
      2: 'var(--na-space-2)',
      2.5: 'var(--na-space-2-5)',
      3: 'var(--na-space-3)',
      3.5: 'var(--na-space-3-5)',
      4: 'var(--na-space-4)',
      5: 'var(--na-space-5)',
      6: 'var(--na-space-6)',
      7: 'var(--na-space-7)',
      8: 'var(--na-space-8)',
      10: 'var(--na-space-10)',
      12: 'var(--na-space-12)',
      14: 'var(--na-space-14)',
      16: 'var(--na-space-16)',
      20: 'var(--na-space-20)',
      24: 'var(--na-space-24)',
      28: 'var(--na-space-28)',
      32: 'var(--na-space-32)',
      full: '100%',
      screen: '100vh',
    },
    fontFamily: {
      display: 'var(--na-font-display)',
      serif: 'var(--na-font-display)',
      sans: 'var(--na-font-body)',
      mono: 'var(--na-font-mono)',
    },
    fontSize: {
      micro: ['var(--na-text-micro)', 'var(--na-leading-body)'],
      overline: ['var(--na-text-overline)', 'var(--na-leading-body)'],
      xs: ['var(--na-text-label)', 'var(--na-leading-compact)'],
      sm: ['var(--na-text-caption)', 'var(--na-leading-compact)'],
      base: ['var(--na-text-body)', 'var(--na-leading-body)'],
      lg: ['var(--na-text-body-large)', 'var(--na-leading-body)'],
      xl: ['var(--na-text-feature-title)', 'var(--na-leading-heading)'],
      '2xl': ['var(--na-text-h4)', 'var(--na-leading-heading)'],
      '3xl': ['var(--na-text-h3)', 'var(--na-leading-tight)'],
      '4xl': ['var(--na-text-h2)', 'var(--na-leading-heading)'],
      '5xl': ['var(--na-text-section)', 'var(--na-leading-heading)'],
      '6xl': ['var(--na-text-display)', 'var(--na-leading-tight)'],
      '7xl': ['var(--na-text-display)', 'var(--na-leading-tight)'],
    },
    boxShadow: {
      none: 'var(--na-shadow-none)',
      sm: 'var(--na-shadow-ring-subtle)',
      DEFAULT: 'var(--na-shadow-ring)',
      md: 'var(--na-shadow-card)',
      lg: 'var(--na-shadow-card)',
      xl: 'var(--na-shadow-overlay)',
      inner: 'var(--na-shadow-inset)',
      ring: 'var(--na-shadow-ring)',
      focus: 'var(--na-shadow-focus)',
    },
    extend: {
      borderRadius: {
        none: 'var(--na-space-0)',
        sm: 'var(--na-radius-sharp)',
        DEFAULT: 'var(--na-radius-control)',
        md: 'var(--na-radius-control)',
        lg: 'var(--na-radius-input)',
        xl: 'var(--na-radius-card)',
        '2xl': 'var(--na-radius-panel)',
        '3xl': 'var(--na-radius-hero)',
        full: 'var(--na-radius-full)',
        'semi-border-radius-extra-small':
          'var(--semi-border-radius-extra-small)',
        'semi-border-radius-small': 'var(--semi-border-radius-small)',
        'semi-border-radius-medium': 'var(--semi-border-radius-medium)',
        'semi-border-radius-large': 'var(--semi-border-radius-large)',
        'semi-border-radius-circle': 'var(--semi-border-radius-circle)',
        'semi-border-radius-full': 'var(--semi-border-radius-full)',
      },
    },
  },
  plugins: [],
};
